### ISSUE TITLE
lodash

### ISSUE THREAD

**Issue by andreineculau** [tobiipro/http-lambda#1]
given the size of lodash, and given the tiny size of the http-lambda package,

1. lodash could actually become a peer dependency, and decrease the bundle size in projects where lodash is a dependency anyway
2. remove the dependency on lodash, which would have effects on load time as well (less js to parse)

My suggestion is to do it in two steps, as listed above

**Comment by IanSavchenko** [comment]
I agree.
But a question here: if we specify `lodash` dependency as a regular one (not peer) something like "^4.0.0", it still won't reuse a project top-level lodash, because we use "global-style" `node_modules` checkout in some repos?

**Comment by andreineculau** [comment]
yup. every global-style dep will have its own lodash, plus maybe another lodash (the root package needs lodash)

**Comment by andreineculau** [comment]
should be less of a problem now with semver ranges in place, and with a slightly optimized lambda dist (i.e. `npm dedupe`). closing
